version: '2.1'
services:
  delegation-service:
    image: delegation-service:latest
    build: .
    ports:
      - '8080:8080'
    environment:
      DEL_PROT: 8080
      DEL_SPIKE_REQUIRED: 'false'
      PHONE_BOOK_URL: 'http://phonebook:8200'
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  phonebook:
    image: registry.gitlab.com/yesodot/shared-projects/dropbox/phonebook-api
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://mongo
      MONGODB_NAME: people
      TERMINAL_URL: http://terminal-mock-api:8080
      PORT: 8200
    depends_on:
      - terminal-mock-api
      - mongo
    ports:
      - 8081:8200

  terminal-mock-api:
    image: registry.gitlab.com/yesodot/shared-projects/dropbox/terminal-mock-api
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - '8082:8080'

  mongo:
    image: mongo:4.0.9
    ports:
      - "27017:27017"
    volumes:
      - ../data/db:/data/db
